server:
  port: 8080

spring:
  application:
    name: wechat-elderly-service
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai

jwt:
  secret: "change-this-secret-key-please-32chars-min"
  expire-hours: 168

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
